spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: root#pass
    dbcp:
      driverClassName: com.mysql.jdbc.Driver
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 30000
      validation-query: SELECT 1
      test-while-idle: true
  # ===============================
  # = JPA / HIBERNATE      
  # ===============================
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
