server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  data:
    mongodb:
      host: 127.0.0.1
      database: yimym
      port: 27017
      username: root
      password: nomes_8129@yimym